In [32]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
from scipy import stats

import statsmodels.api as sm 
import statsmodels.formula.api as smf

In [23]:
from sklearn.metrics import confusion_matrix

In [4]:
dft = pd.read_csv('Default.csv')
dft.head()

default student      balance        income
0      No      No   729.526495  44361.625074
1      No     Yes   817.180407  12106.134700
2      No      No  1073.549164  31767.138947
3      No      No   529.250605  35704.493935
4      No      No   785.655883  38463.495879

In [11]:
dft['studentYes'] = (dft['student'] == 'Yes').astype(np.int)
dft['defaultYes'] = (dft['default'] == 'Yes').astype(np.int)
dft['income'] = dft['income'] / 1000
dft.head()

/Users/goyunjae/opt/miniconda3/envs/ML2020/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.
/Users/goyunjae/opt/miniconda3/envs/ML2020/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the pre

default student      balance    income  studentYes  defaultYes
0      No      No   729.526495  0.000044           0           0
1      No     Yes   817.180407  0.000012           1           0
2      No      No  1073.549164  0.000032           0           0
3      No      No   529.250605  0.000036           0           0
4      No      No   785.655883  0.000038           0           0

In [21]:
fit1 = smf.glm(formula = 'defaultYes ~ studentYes', data = dft, family = sm.families.Binomial()).fit()
fit1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:             defaultYes   No. Observations:                10000
Model:                            GLM   Df Residuals:                     9998
Model Family:                Binomial   Df Model:                            1
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -1454.3
Date:                Sun, 05 Sep 2021   Deviance:                       2908.7
Time:                        22:19:33   Pearson chi2:                 1.00e+04
No. Iterations:                     6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -3.5041      0.071    -49.554      0.000      -3.643      -3.366
studentYes     0.4049      0.115      3.520      0.000       0.179       0.630
==============================================================================
"""

In [15]:
dir(fit1)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_cache',
 '_data_attr',
 '_data_attr_model',
 '_data_in_cache',
 '_endog',
 '_freq_weights',
 '_get_robustcov_results',
 '_iweights',
 '_n_trials',
 '_use_t',
 '_var_weights',
 'aic',
 'bic',
 'bic_deviance',
 'bic_llf',
 'bse',
 'conf_int',
 'converged',
 'cov_kwds',
 'cov_params',
 'cov_type',
 'deviance',
 'df_model',
 'df_resid',
 'f_test',
 'family',
 'fit_history',
 'fittedvalues',
 'get_hat_matrix_diag',
 'get_influence',
 'get_prediction',
 'initialize',
 'k_constant',
 'llf',
 'llnull',
 'load',
 'method',
 'mle_settings',
 'model',
 'mu',
 'nobs',
 'normalized_cov_params',
 'null',
 'null_deviance',
 'params',


In [18]:
conf = fit1.conf_int()
conf['coef'] = fit1.params
conf.columns = ['2.5%', '97.5%', 'coef']
conf

2.5%     97.5%      coef
Intercept  -3.642723 -3.365533 -3.504128
studentYes  0.179454  0.630320  0.404887

In [20]:
conf_or = np.exp(conf)
conf_or.columns = ['2.5%', '97.5%', 'odds ratio']
print(conf_or)

                2.5%     97.5%  odds ratio
Intercept   0.026181  0.034544    0.030073
studentYes  1.196564  1.878211    1.499133


In [22]:
fit = smf.glm(formula = 'defaultYes ~ balance + income + studentYes', data = dft, family = sm.families.Binomial()).fit()
fit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:             defaultYes   No. Observations:                10000
Model:                            GLM   Df Residuals:                     9996
Model Family:                Binomial   Df Model:                            3
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -785.77
Date:                Sun, 05 Sep 2021   Deviance:                       1571.5
Time:                        22:19:37   Pearson chi2:                 7.00e+03
No. Iterations:                     9                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -10.8690      0.492    -22.079      0.000     -11.834      -9.904
balance        0.0057      0.000     24.737      0.000       0.005       0.006
income      3033.4501   8202.766      0.370      0.712    -1.3e+04    1.91e+04
studentYes    -0.6468      0.236     -2.738      0.006      -1.110      -0.184
==============================================================================
"""

In [27]:
conf99 = pd.DataFrame()
conf99['0.5%'] = fit.params + stats.norm.ppf(0.005)*fit.bse
conf99['99.5%'] = fit.params + stats.norm.ppf(0.995)*fit.bse
print(conf99)

                    0.5%         99.5%
Intercept     -12.137056     -9.601035
balance         0.005139      0.006334
income     -18095.473912  24162.374151
studentYes     -1.255333     -0.038218


In [28]:
dft["defaultYes"].value_counts()

0    9667
1     333
Name: defaultYes, dtype: int64

In [30]:
pred_p = fit.predict()   
pred_c1 = [ 1 if x > 0.5 else 0 for x in pred_p]
print(confusion_matrix(dft["defaultYes"], pred_c1))  

[[9627   40]
 [ 228  105]]


In [31]:
pred_c2 = [ 1 if x > 0.02 else 0 for x in pred_p]
print(confusion_matrix(dft["defaultYes"], pred_c2))

[[7929 1738]
 [  26  307]]


In [34]:
bank = pd.read_table('bankrupt.txt', sep="\s+")
bank.head()

x1    x2    x3    x4  y
0 -0.45 -0.41  1.09  0.45  0
1 -0.56 -0.31  1.51  0.16  0
2  0.06  0.02  1.01  0.40  0
3 -0.07 -0.09  1.45  0.26  0
4 -0.10 -0.09  1.56  0.67  0

In [37]:
fm = smf.glm(formula = 'y ~ x1 + x2 + x3 + x4', data = bank, family = sm.families.Binomial()).fit()
fm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:                      y   No. Observations:                   46
Model:                            GLM   Df Residuals:                       41
Model Family:                Binomial   Df Model:                            4
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -13.722
Date:                Tue, 07 Sep 2021   Deviance:                       27.443
Time:                        14:40:29   Pearson chi2:                     54.1
No. Iterations:                     7                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -5.3195      2.366     -2.248      0.025      -9.958      -0.681
x1             7.1378      6.002      1.189      0.234      -4.625      18.901
x2            -3.7033     13.670     -0.271      0.786     -30.497      23.090
x3             3.4148      1.204      2.837      0.005       1.056       5.774
x4            -2.9684      3.065     -0.968      0.333      -8.976       3.040
==============================================================================
"""

In [38]:
fm0=smf.glm(formula = 'y ~ 1', 
           data=bank, family=sm.families.Binomial()).fit()
(fm.llf-fm0.llf)*2, -fm.llf*2

(35.97804036473356, 27.443234484469368)

In [39]:
from sklearn.model_selection import train_test_split

bank_train, bank_test = train_test_split(bank, test_size=0.3, random_state=10)
bank.shape, bank_train.shape, bank_test.shape

((46, 5), (32, 5), (14, 5))

In [41]:
from sklearn.model_selection import KFold

scores1 = np.zeros(5)
scores2 = np.zeros(5)
cv = KFold(5, shuffle=True, random_state=0)

for i, (idx_train, idx_test) in enumerate(cv.split(bank)):
    bank_train = bank.iloc[idx_train]
    bank_test = bank.iloc[idx_test]
    
    yte=bank_test["y"]

    fm1_tr=smf.glm(formula = 'y ~ x1 + x3 ', 
           data=bank_train, family=sm.families.Binomial()).fit()
    fm2_tr=smf.glm(formula = 'y ~ x1 + x2 + x3 + x4', 
           data=bank_train, family=sm.families.Binomial()).fit()
    
    p=fm1_tr.predict(bank_test)
    scores1[i] = -(yte*np.log(p)+(1-yte)*np.log(1-p)).sum()   

    p=fm2_tr.predict(bank_test)
    scores2[i] = -(yte*np.log(p)+(1-yte)*np.log(1-p)).sum()

scores1.mean(), scores2.mean()

(5.520810647011531, 7.206015359368318)

In [42]:
from sklearn.linear_model import LogisticRegression 

In [45]:
X = bank.values[:,:4]
y = bank.values[:,4]
log_reg = LogisticRegression(penalty='none')    
fit1 = log_reg.fit(X,y)
print(fit1.intercept_)
print(fit1.coef_)

[-5.31951669]
[[ 7.13779753 -3.70328691  3.4148359  -2.96838772]]


In [46]:
log_reg=LogisticRegression(solver='newton-cg', penalty='none')    
fit1=log_reg.fit(X,y)
print(fit1.intercept_)
print(fit1.coef_)

[-5.31951257]
[[ 7.13780424 -3.70332948  3.41483434 -2.96839048]]


In [49]:
LogisticRegression?

In [47]:
log_reg=LogisticRegression(solver='sag', penalty='none')    
fit1=log_reg.fit(X,y)
print(fit1.intercept_)
print(fit1.coef_)

[-4.74348487]
[[ 4.64539901  1.76963627  3.16156161 -2.97825575]]


/Users/goyunjae/opt/miniconda3/envs/ML2020/lib/python3.7/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


## 다항

In [51]:
from sklearn import datasets
iris = datasets.load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [52]:
import statsmodels.formula.api as smf
X = iris['data'][:,(2,3)]                     
y = iris['target']
data=pd.DataFrame(np.c_[X,y],columns=['x1','x2','y'])
fit_mn1 = smf.mnlogit(formula='y~x1+x2',data=data).fit(method='ncg')
print(fit_mn1.summary())

         Current function value: 0.068555
         Iterations: 35
         Function evaluations: 36
         Gradient evaluations: 36
         Hessian evaluations: 35
                          MNLogit Regression Results                          
Dep. Variable:                      y   No. Observations:                  150
Model:                        MNLogit   Df Residuals:                      144
Method:                           MLE   Df Model:                            4
Date:                Tue, 07 Sep 2021   Pseudo R-squ.:                  0.9376
Time:                        16:03:00   Log-Likelihood:                -10.283
converged:                      False   LL-Null:                       -164.79
Covariance Type:            nonrobust   LLR p-value:                 1.229e-65
       y=1       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -27.2178     90.934     -0.299

/Users/goyunjae/opt/miniconda3/envs/ML2020/lib/python3.7/site-packages/statsmodels/base/model.py:568: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)


In [53]:
import statsmodels.formula.api as smf
X = iris['data'][:,(2,3)]                     
y = iris['target']
data=pd.DataFrame(np.c_[X,y],columns=['x1','x2','y'])
fit_mn1 = smf.mnlogit(formula='y~x2',data=data).fit(method='ncg')
print(fit_mn1.summary())

         Current function value: 0.111439
         Iterations: 35
         Function evaluations: 36
         Gradient evaluations: 36
         Hessian evaluations: 35
                          MNLogit Regression Results                          
Dep. Variable:                      y   No. Observations:                  150
Model:                        MNLogit   Df Residuals:                      146
Method:                           MLE   Df Model:                            2
Date:                Tue, 07 Sep 2021   Pseudo R-squ.:                  0.8986
Time:                        16:06:03   Log-Likelihood:                -16.716
converged:                      False   LL-Null:                       -164.79
Covariance Type:            nonrobust   LLR p-value:                 4.914e-65
       y=1       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -26.5489     53.603     -0.495

/Users/goyunjae/opt/miniconda3/envs/ML2020/lib/python3.7/site-packages/statsmodels/base/model.py:568: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)


In [54]:
import statsmodels.api as sm

X = iris['data'][:,(2,3)]                     
X = sm.add_constant(X)
y = iris['target']

fit_mn1a = sm.MNLogit(y, X).fit(method='ncg')
print(fit_mn1a.summary())

         Current function value: 0.068555
         Iterations: 35
         Function evaluations: 36
         Gradient evaluations: 36
         Hessian evaluations: 35
                          MNLogit Regression Results                          
Dep. Variable:                      y   No. Observations:                  150
Model:                        MNLogit   Df Residuals:                      144
Method:                           MLE   Df Model:                            4
Date:                Tue, 07 Sep 2021   Pseudo R-squ.:                  0.9376
Time:                        16:07:25   Log-Likelihood:                -10.283
converged:                      False   LL-Null:                       -164.79
Covariance Type:            nonrobust   LLR p-value:                 1.229e-65
       y=1       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        -27.2178     90.933     -0.299

/Users/goyunjae/opt/miniconda3/envs/ML2020/lib/python3.7/site-packages/statsmodels/base/model.py:568: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)
